linters:
  enable-all: true
  disable:
    - errcheck
    - exhaustivestruct
    - lll
    - testpackage
    - wrapcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
