language: go
sudo: false
go:
  - 1.11.x
  - tip
install:
  - go get honnef.co/go/tools/cmd/staticcheck
  - go mod download
script:
  - staticcheck
  - go test -race -coverprofile=coverage.txt -covermode=atomic
env:
  - GO111MODULE=on
after_success: bash <(curl -s https://codecov.io/bash)
