language: go
sudo: false
go:
  - 1.10.x
  - 1.11.x
  - tip
install:
  - go get -v github.com/golang/dep/cmd/dep golang.org/x/lint/golint
  - dep ensure -v
script:
  - golint -set_exit_status
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success: bash <(curl -s https://codecov.io/bash)
