[[constraint]]
  branch = "master"
  name = "github.com/Gurpartap/logrus-stack"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.2.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/knq/sdhook"

[[constraint]]
  branch = "master"
  name = "github.com/marzagao/logrus-env"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[prune]
  go-tests = true
  unused-packages = true
